### ISSUE TITLE
new forge universal jar

### ISSUE THREAD

**Issue by maksimetny** [Pierce01/MinecraftLauncher-core#14]
in the new universal forge for 1.14.2, version.json is missing and the getForgeDependencies function does not work correctly.

tested on new version 1.14.2 with forge version 26.0.63
https://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.14.2.html

![image](https://user-images.githubusercontent.com/46288028/60396235-560a2700-9b47-11e9-9d93-59603c4c1857.png)

**Comment by Pierce01** [comment]
This is a known issue that has been discussed in the discord. I wont be able to update the function until the 18th as I'm in Japan without a laptop.

**Comment by maksimetny** [comment]
It will be great if the problem is solved. I'll try to solve it myself

**Comment by Pierce01** [comment]
The issue arises due to the fact it doesnt contain the version file in the universal jar. However, after installing forge through the installer, the version file has been changed to the latest version file format, so getForgeDeps is outdated.

I'll work to fix this when I get home. If need to contact me, feel free to join the discord and shoot me a message

**Comment by Pierce01** [comment]
Hi there. Forge 1.14.2 can now be launched with MCLC. I'll add proper docs explaining how to.
