### ISSUE TITLE
Program stops directly after downloading assets.

### ISSUE THREAD

**Issue by Hallzmine** [Pierce01/MinecraftLauncher-core#45]
I am trying to use this npm package inside of an electron app to start minecraft but instead it refuses to launch. Here is my terminal log https://pastebin.com/pMjGEbaz My code is simply https://pastebin.com/sJKs8rt8

**Comment by NoXeDev** [comment]
The program stopping when the Auth parameter is invalid, change your auth parameter, you can delete your password for disable online, or if you have buy minecraft, enter your good auth.

**Comment by Bricklou** [comment]
![image](https://user-images.githubusercontent.com/15181236/81539521-a7429400-9370-11ea-83bc-7fdd628e3001.png)
Please separate the auth process from the launch process. You need to created an error handle otherwise your program won't be able to work fine.

You can also come on the discord server for more support there: https://discord.gg/8uYVbXP

**Comment by Pierce01** [comment]
Hey there, going off of what Bricklou said, in PRODUCTION settings it's best you handle authentication outside the launch object, however, if you're just testing you should be fine. Your error is caused by an incorrect password, so simply remove `,"password"` in getAuth to fix your issue. Thanks for using my project :)
